# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('tcp-error-model-test', ['hidden-markov-model'])
    obj.source = 'tcp-error-model-test.cc'

