## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
def configure(conf): 
    conf.env.append_value('LINKFLAGS', ['-lcrypto', '-lgsl', '-lgslcblas'])
    #conf.env.append_value('CXXFLAGS', '-zmuldefs')

    have_itpp = conf.pkg_check_modules('IT++', 'itpp', mandatory=True)
    conf.env['ENABLE_ITPP'] = have_itpp
    conf.report_optional_feature("IT++", "IT++ library",
                                 conf.env['ENABLE_ITPP'],
                                 "IT++ not found")
    if conf.env['ENABLE_ITPP']:
        conf.env.append_value('CXXFLAGS', '-DNO_INT_SIZE_CHECK')

def build(bld):
    obj = bld.create_ns3_module('network-coding', ['core','wifi','network','internet','propagation'])
    obj.source = [
        'model/network-coding-l4-protocol.cc',
        'model/inter-flow-network-coding-protocol.cc',        
        'model/inter-flow-network-coding-header.cc',
        'model/inter-flow-network-coding-buffer.cc',
        'model/intra-flow-network-coding-protocol.cc',     
        'model/intra-flow-network-coding-header.cc',   
        'helper/network-coding-helper.cc'          
        ] 

    obj_test = bld.create_ns3_module_test_library('network-coding')
    obj_test.source = [
        'test/network-coding-test-suite.cc',
        ]    

    headers = bld.new_task_gen(features=['ns3header'])  
    headers.module = 'network-coding'
    headers.source = [
        'model/network-coding-l4-protocol.h',
        'model/inter-flow-network-coding-protocol.h',        
        'model/inter-flow-network-coding-header.h',
        'model/inter-flow-network-coding-buffer.h',
        'model/intra-flow-network-coding-protocol.h',     
        'model/intra-flow-network-coding-header.h',  
        'helper/network-coding-helper.h'          
        ]

    #if bld.env.ENABLE_EXAMPLES:
    #    bld.add_subdirs('examples')

    if bld.env['ENABLE_ITPP']:
        obj.uselib = 'IT++'
        obj.env.append_value('CXXDEFINES', "ENABLE_ITPP")

    obj.env.append_value('LINKFLAGS', '-lcrypto')

    #if bld.env['ENABLE_GSL']:
          #obj.use.extend(['GSL', 'GSLCBLAS', 'M'])
          #obj_test.use.extend(['GSL', 'GSLCBLAS', 'M'])
       
  #  bld.ns3_python_bindings()