# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('bear-model', ['core','wifi','network','internet','propagation'])
    module.source = [
        'model/bear-model-entry.cc',
        'model/bear-propagation-loss-model.cc',
        'model/bear-error-model.cc'         
        ]

    module_test = bld.create_ns3_module_test_library('bear-model')
    module_test.source = [
        'test/bear-model-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'bear-model'
    headers.source = [
        'model/bear-model-entry.h',
        'model/bear-propagation-loss-model.h',
        'model/bear-error-model.h'    
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

